// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using etip.Data;

#nullable disable

namespace etip.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250415072546_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("etip.Models.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("etip.Models.ParkingRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DailyMaxRate")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FirstHourRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NextHourRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OverDuePinaltyPerDay")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("ParkingRates");
                });

            modelBuilder.Entity("etip.Models.ParkingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("FinalFee")
                        .HasColumnType("numeric");

                    b.Property<int>("InTapOperatorId")
                        .HasColumnType("integer");

                    b.Property<int>("OutTapOperatorId")
                        .HasColumnType("integer");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TapInTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TapOutTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InTapOperatorId");

                    b.HasIndex("OutTapOperatorId");

                    b.ToTable("ParkingSessions");
                });

            modelBuilder.Entity("etip.Models.ParkingSession", b =>
                {
                    b.HasOne("etip.Models.Operator", "InTapOperator")
                        .WithMany("TapInSessions")
                        .HasForeignKey("InTapOperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("etip.Models.Operator", "OutTapOperator")
                        .WithMany("TapOutSessions")
                        .HasForeignKey("OutTapOperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InTapOperator");

                    b.Navigation("OutTapOperator");
                });

            modelBuilder.Entity("etip.Models.Operator", b =>
                {
                    b.Navigation("TapInSessions");

                    b.Navigation("TapOutSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
